// Calculator.idl - COM インターフェース定義

import "oaidl.idl";
import "ocidl.idl";

[object, uuid(12345678-1234-1234-1234-123456789001)]
interface ICalculator : IUnknown
{
    HRESULT Add([in] int a, [in] int b, [out, retval] int* result);
    HRESULT Subtract([in] int a, [in] int b, [out, retval] int* result);
    HRESULT Multiply([in] int a, [in] int b, [out, retval] int* result);
    HRESULT Divide([in] int a, [in] int b, [out, retval] int* result);
};

// クラス定義（CLSID を追加）
[uuid(87654321-4321-4321-4321-098765432100)]
coclass Calculator
{
    [default] interface ICalculator;
};

[version(1.0), uuid(87654321-4321-4321-4321-987654321000)]
library CalculatorLib
{
    interface ICalculator;
    coclass Calculator;
};